- name: Collect information relevant to incident response
  hosts: all

  tasks:
    - name: Query recent logons
      command: osqueryi "SELECT * FROM last WHERE time > (SELECT unix_time FROM time)-43200;"
      register: recent_logons
    - debug: var=recent_logons.stdout_lines

    - name: Query process info
      command: osqueryi "SELECT pid, name, parent, path, on_disk as 'on disk', total_size as 'total size', user_time as 'user time', system_time AS 'system time' FROM processes;"
      register: process_info
    - debug: var=process_info.stdout_lines

    - name: Query outbound connections(not port 80 or 443)
      command: osqueryi "SELECT * FROM process_open_sockets WHERE remote_address NOT IN  ('', '::', '0.0.0.0') AND remote_port NOT IN (80, 443);"
      register: outbound_conns
    - debug: var=outbound_conns.stdout_lines